Refactor/xacro launch generic elite description - generic elite arm robot description
neobotix/elite-robots2 pull request #63
Opened 2024-06-29 11:31 UTC by AdarshKaran

Added use_gazebo and use_arm_type arguments,  changed urdf to give flexibility to use other elite arms by just adding meshes and config files, renamed filed

2024-07-02 13:15 UTC, padhupradheep requested changes
Overall LGTM! 

Could you please make a short video including the execution of MoveIt packages?

2024-07-02 13:15 UTC, padhupradheep commented on elite_moveit/config/ec66_simulation.urdf.xacro
> +    <xacro:include filename="$(find elite_description)/urdf/ec66_description.urdf.xacro">
I think you need to update this.

2024-07-08 23:32 UTC, AdarshKaran commented
i have made the updates to the elite packages anna. kindly let me know if it is okay. I will then add the functionality for cs66 arm too

2024-07-10 12:44 UTC, padhupradheep commented
But there is still an issue with the MoveIt package right?

2024-07-10 22:14 UTC, AdarshKaran commented
yes anna. But, the description files were updated.

2025-05-06 13:59 UTC, padhupradheep commented
Is this PR still relevant?

2025-05-08 06:45 UTC, AdarshKaran commented
No Pradheep. the migration and refactoring has been addressed in pr #64 . this can be closed without merging

2025-05-08 07:03 UTC, closed without merging